analytics: {}
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0
name: danmanmj
opengraph: {}
purpose: []
typography_spectrum: 0.88673
