typography_spectrum: 0.89717
content_rating:
  adult: false
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Daniel Moriss-Jeffery
  email: danmanmj@gmail.com
name: danmanmj
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Photography Website
purpose: []
